### ISSUE TITLE
DijkstraMap findPath doc improvement

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#117]
The javadoc for findPath doesn't mention that the path it returns is a cached instance. Without that bit of knowledge, the sample project that is built having a line that builds a new ArrayList from the path returned doesn't make sense. I _think_ there used to be documentation about how the path is cached at the class level, but I didn't see it in my brief lookabout.

I'm not really sure why path is cached at the class level actually, path = new ArrayList<>() still gets called in findPath() instead of path.clear()

Maybe just returning a new path from each call so the end user doesn't have to do so on their end would make sense?

**Comment by tommyettinger** [comment]
This has been fixed since commit https://github.com/SquidPony/SquidLib/commit/7a4bcf25c1b2b063500fd1065132b11d43a91b68 , 5 days ago. I thought the mention in the commit message would close it, but I guess it doesn't.
