### ISSUE TITLE
Setting RNG on probability tables after creation

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#138]
I find myself wanting to instantiate probability tables from JSON objects and want to change their RNG to a new one after creation.

Really the best thing for me would be the ability to in one place set the RNG that all things that need one would use. If that's not doable then setting them per class might be fine as well, but it seems like a single static RNG at the class level might also be not great. I'm not really sure what the best option here actually is, unfortunately.

**Comment by tommyettinger** [comment]
I haven't used the probability table code, and need to get more familiar with it. Recursive probability tables may be trickier to serialize to JSON (or XML, or YAML, or any non-binary format...), which I think is what #137 is suggesting.

To answer your second paragraph, is seeding important here, or is the code just saying "gimme some random values" and passing, say, null for an RNG parameter? Using static fields has some issues on Android, where the lifetime of a static variable can be longer than one run of the application/game (previous calls to a static RNG variable may or may not have the consequential change to state persist over more than one play of the game, on Android). A solution may be using StatefulRNG, which allows setting the state/seed after-the-fact and also getting the current state as a long.

**Comment by SquidPony** [comment]
Seeding would be important there, but good point about Android statics.

The StatefulRNG might be a reasonable solution by the sound of it. I haven't used that one yet

**Comment by tommyettinger** [comment]
There's currently code in ProbabilityTable to set the RNG to a different reference, but you can also give the constructor a StatefulRNG and keep it around to change the state with its `setState(long)` method or obtain the current state with `getState(long)`. The RNG is not copied, and is instead shared with any other usage of that variable, so that should do most of what you want.
