### ISSUE TITLE
DijkstraMap initialize(double[][] level) is unclear

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#159]
Given initializeCost also exists, it's unclear what the difference is, except that the cost related mehod requires special handling for fully impassible objects. What values are expected from non-cost initialization? Using values from 0 (walkable) to 1 (impassible) does not seem to work

**Comment by tommyettinger** [comment]
Costs were added much later; the `double[][]` constructor pre-fills the field called (internally at least, maybe also publicly visible) `gradientMap`. This can be useful if you have an existing DijkstraMap and want to operate on a copy of it to do things like what `findFleePath()` does, getting paths to cells in an existing DijkstraMap result with optimal values for some constraint. This constructor isn't used internally in DijkstraMap, but `initialize(final double[][] level)` is (mostly in AOE implementations), and that's what this constructor mainly calls.

The values expected for the doubles in that array are the same types of values in the array that `scan()` produces, so `DijkstraMap.WALL` or higher will be considered blocked, and anything else is a walkable cell that either contains a distance to a goal, or that hasn't been scanned yet (this case should be `DijkstraMap.FLOOR`). There may be some good options in the future for using `GreasedRegion` or another `Collection<Coord>` to simply mark all cells in that collection as passable or impassable, but that code isn't present yet.
