### ISSUE TITLE
It would be nice to have DijkstraMap's straight-ish line directly settable to some styles

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#164]
I'm thinking of the following, with the last one most strongly desired. ("Always" and "Never" mean when choosing between equally length paths only)

Always prefer horizontal

Always prefer vertical

Always prefer diagonal last

Always prefer diagonal first

Always spread out diagonal across the entire length as evenly as possible

Never switchback

**Comment by tommyettinger** [comment]
I have no idea what this is referring to. Can you elaborate?

**Comment by SquidPony** [comment]
The blue arrows point to sections that could instead be straight, as an example

![choices](https://user-images.githubusercontent.com/1217477/27256082-8c589796-5360-11e7-9e12-de60bbc94354.png)

Which actually points out that the above list should include "Never switchback"

**Comment by tommyettinger** [comment]
Looks like you're using Chebyshev; try Euclidean and see what happens.

**Comment by SquidPony** [comment]
In this picture you can see that it went full horizontal then vertical at the line but it could have made that alternating for a diagonal overall
![angles](https://user-images.githubusercontent.com/1217477/27256198-fb73fe34-5362-11e7-9914-ca25c477b9e9.png)

**Comment by tommyettinger** [comment]
That looks like Manhattan in the latest image. I don't know how it would work for the paths to be able to predict future directions and change movement to fit; currently this is randomized and you got a bad draw.

**Comment by SquidPony** [comment]
Yeah, I switched to Manhattan for that last one since what I meant is clearest there. Euclidean does seem to do better than Chebyshev, fwiw.

I think what I'm really asking for here is more complex than just adding a feature to DijkstraMap. I'll close this issue since it's now been discussed and there's not much reason to make any changes.
