### ISSUE TITLE
putString with background color seems to be wrong

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#167]
![background wrong](https://user-images.githubusercontent.com/1217477/27840019-8903a552-60aa-11e7-8b65-ffeae53a028b.png)

code:
`contextPanel.putString(5, 3, "CONTEXT", SColor.KIMONO_STORAGE, SColor.LIGHT_LIME); `

No idea why the background doesn't fill the same space as the text

**Comment by tommyettinger** [comment]
Assuming contextPanel is a SquidLayers with a misleading name, this is a bug, and it has just been fixed. I'll see if GitHub can notice it in a commit message.

**Comment by SquidPony** [comment]
It is indeed a SquidLayers with a misleading name... I'll go refactor my names :)
