### ISSUE TITLE
RNG getRandomUniqueCells returning out of bound Coord values

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#171]
With this code
`        for (Coord coord : rng.getRandomUniqueCells(0, 0, map.width, map.height))
            System.out.println("Testing map (" + map.width + ", " + map.height + ") found Coord: " + coord);`

I'm getting this output
`Testing map (100, 50) found Coord: (45,83)`

My theory is that x and y are swapped somewhere

**Comment by tommyettinger** [comment]
Good catch! Writing some tests now. I think I found what's causing the bug (you're probably right, it seems to have mixed up `%` and `/` for x and y), and I want to verify.
