### ISSUE TITLE
SquidLayers clear(int x, int y) documentation is misleading regarding what it does

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#176]
`
    /**
     * Clear one cell at position x, y of  its foreground contents.
     * <p>
     * You may be looking for the erase() method, which erases all panels and all cells.
     *
     * @param x in grid cells
     * @param y in grid cells
     * @return this for chaining
     */
    public SquidLayers clear(int x, int y) {
        foregroundPanel.clear(x, y);
        return this;
    }`

Has a side effect of setting that backing character to null rather than a space. This means that while the tile is set to clear when this is called if the backing character set is accessed (to cache off in my case) and then used again later a solid block instead of a clear block is placed there.

I'm not sure if the correct fix is to just change the documentation to make that side effect clear or to change the way the method works to do what the doc says. Either way is probably fine.

**Comment by tommyettinger** [comment]
This is pretty much a bug, yeah. Since erase() fills with space, clear() should too. I have a commit ready that fixes this, though I need to ensure I can pull OK.
