### ISSUE TITLE
setPosition on SquidPanel?

### ISSUE THREAD

**Issue by Rakaneth** [SquidPony/SquidLib#186]
I am not sure if I'm doing this incorrectly or if something is wrong, but `SquidPanel.setPosition()` does not seem to be placing the `SquidPanel` in the correct position.

		display.setBounds(0, msgHeight * cellHeight, gridWidth * cellWidth, gridHeight * cellHeight);
		msgs.setBounds(0, 0, msgWidth * cellWidth, msgHeight * cellHeight);
		statPanel = new SquidPanel(statWidth, statHeight, tcf.copy());
		statPanel.setPosition(960, 0);
		stage.addActor(display);
		stage.addActor(msgs);
		stage.addActor(statPanel);
		Gdx.input.setInputProcessor(new InputMultiplexer(stage, input));
		msgs.appendMessage(GDXMarkup
        .instance
        .colorString("[Green]Welcome[] to Wolf's Den II!"));
	}
	
	@Override
	public void render()
	{
		super.render();
		if (input.hasNext()) input.next();
		putCenter(display, "Play Screen", 10, SColor.MEDIUM_CRIMSON);
		putCenter(display, "[Esc] to return to title", 11, SColor.MEDIUM_CRIMSON);
		statPanel.put(0, 0, "Test String");
		stage.draw();
		stage.act();
	}

This is the result:

![image](https://user-images.githubusercontent.com/19420583/32377286-7f1f2f2e-c07d-11e7-9f1e-cad946795fad.png)

I am expecting the Test String to be to the right of the Play Screen.

**Comment by tommyettinger** [comment]
I'll look into this; it looks like either a bug in SquidLib or one of the many quirks involved with using libGDX's scene2d.ui components. I think the code you supplied should be enough to figure this out, thanks.

**Comment by tommyettinger** [comment]
This should be fixed now; running the new PositionTest (based on your code to replicate the issue), I get a screen that looks like 
![java_2017-11-03_14-57-39](https://user-images.githubusercontent.com/160684/32400043-d65ca3e4-c0b8-11e7-9d43-663bb5081e75.png).

**Comment by tommyettinger** [comment]
Also, you should clear the screen if you don't already at the start of render(). Without that, the alpha-blended curves on text overlap many times, and look extremely thick and bold. This looks like: 
![java_2017-11-03_17-05-27](https://user-images.githubusercontent.com/160684/32400106-46e6d0da-c0b9-11e7-8f77-804a90bc1347.png).
