### ISSUE TITLE
BurstAOE uses a null resistanceMap to calculate its FOV

### ISSUE THREAD

**Issue by Rakaneth** [SquidPony/SquidLib#197]
I am not sure why this is, but at the moment, this causes `BurstAOE.apply` to blow up with a `NullPointerException.`

**Comment by tommyettinger** [comment]
Are you calling `BurstAOE.setMap()` before... whatever method is blowing up? That call should set `resistanceMap` based on the given `char[][]`. Calling setMap() is mentioned throughout the AOE-related docs as a necessary step, but it's possible there's some methods that can be called without needing it, while others will throw exceptions if the map isn't up-to-date. You may have encountered mostly the former kind of method, so there wasn't a need for setMap() in your code until now, maybe?

**Comment by Rakaneth** [comment]
`setMap()` gets called in the constructor for `WolfSkill` (my `Technique` wrapper).

Here is line 517 in BurstAOE.java:
     return AreaUtils.arrayToHashMap(fov.calculateFOV(null, center.x, center.y, radius, radiusType));

**Comment by tommyettinger** [comment]
This should be fixed now. I also checked for any other usages of calculateFOV that passed null directly, and I couldn't find any. Thanks for finding this.
