### ISSUE TITLE
Suggestion : Improvement of String.equals("xxx")

### ISSUE THREAD

**Issue by o0lwj0o** [SquidPony/SquidLib#201]
Hi,
    I have found some usage of “String.equals("xxx")” in your project. 
    For excmple terms[t].equals(";") ，it will get nullpointexception if terms[t] ==null. 
    The problem can be fixed by repalced with   ";".equals(terms[t]) or Objects.equals(terms[t],";"). 

PS:
https://github.com/SquidPony/SquidLib/blob/master/squidlib-util/src/main/java/squidpony/MonsterGen.java | 109/118/125/133/140

**Comment by tommyettinger** [comment]
Thanks for reporting! I wrote that MonsterGen class quite a while ago and haven't looked much at it since; I'll try and see if I'm using non-null-safe String equality checks anywhere else as well. This should be a quick fix.
