### ISSUE TITLE
heightmap toolkit

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#25]
easy methods to create heightmaps of arbitrary size

**Comment by tommyettinger** [comment]
Pfft, Height maps. Think bigger, @SquidPony ! Now we have world maps with height maps, heat maps, moisture maps, biomes, optional political maps, and so on. You can thank @zacharycarter for the original worldgen, he rules.

If this is for a cave's height, then the Noise class offers various ways to mix noise functions to get a suitably organic look (if you have x and y positions, then you can get a Noise.Ridged2D result from x and y,, add that to either the x or y you pass to a Noise.LayeredNoise call, and you already have a nice organic shape resulting from the LayeredNoise call; adjust frequencies to make it have  small or large details). Some of this might warrant some presets for common uses.
