### ISSUE TITLE
Check cuttlebone generation algorithms and determine what to use

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#49]
Probably going to be best to provide overloads so that the speed of byte arrays can be used if they'll work, but the flexibility of String arrays can be used if it's needed.

**Comment by tommyettinger** [comment]
I actually imported the newest cuttlebone strategies last night. This should be able to generate the same styles as stb_herringbone_wang, the original herringbone Wang tile dungeon generator library for C, but without image processing in the stb library's unusual style. It only generates '#' and '.' maps as char [][], but you can run DungeonUtility.hashesToLines () on a char [][] map to get unicode box drawing chars out of it.  More features are coming up to match some stuff I need for my 2-char-creatures design, with @r or the like as a human with a gun, and @} for a human with a bow.
