### ISSUE TITLE
Gdx EverythingDemo - Translation Screen coordinates <--> Tiles broken

### ISSUE THREAD

**Issue by davidbecker** [SquidPony/SquidLib#68]
as I mentioned in #67 the translation from screen coordinates to tiles is off.
First image: mouse is directly hovering over the player tile:
![gdx01mouseoverplayer](https://cloud.githubusercontent.com/assets/1927731/9499284/f2bd73c6-4c1e-11e5-9930-2eea8784d306.png)
Second Image: mouse was moved one tile to the north:
![gdx02mouseonetileaboveplayer](https://cloud.githubusercontent.com/assets/1927731/9499299/039a2ffe-4c1f-11e5-9e34-97e3893ba7da.png)

**Comment by dasmau89** [comment]
I briefly looked at the code and it seems to me that the problem is in the construtor of SquidMouse:

```java
this.gridWidth = Gdx.graphics.getWidth() / cellWidth;
this.gridHeight = Gdx.graphics.getHeight() / cellHeight;
```
This assumes that the size of the window will stay the same at all times (which isn't a save assumtion)

**Comment by tommyettinger** [comment]
Hm. Thinking aloud here... I'm not sure if resize() in SquidMouse would actually get called automatically when the window resizes. I could provide a convenience method to recalculate the gridWidth, gridHeight, cellWidth, and cellHeight all in one go, and users could call it in their game's resize() method. This is just a simpler way of how it is now (you can currently call the setters on each of those four size measurements in your own resize method).
I think your suggestion of using unproject() is probably the best way we have, unless cellWidth and cellHeight are changing when the user resizes.

**Comment by davidbecker** [comment]
I think I was a little unclear: I ment to override the resize method from ApplicationAdapter.
I tinkered a little with the different options and sadly the unproject option doesn't work since gdx and squidlib have different ways of using the y-axis. There is an option to let the camera invert the y-axis but this flips the whole picture upside down.
Since the aspect ration of the tiles changes on a resize as well it seems to me that the only viable way is to recompute the parameters with the new width and height of the screen and the number of tiles in the map

**Comment by tommyettinger** [comment]
I feel like there is probably a better way to write SquidMouse for games with changing cell sizes than the way it is currently done.  For now, I'll write a reinitialize() function that you can call from a resize method or anywhere else when the cell and/or grid sizes change. I updated EverythingDemo to use it from inside the override method `resize(int width, int height)` like so:
```java
input.getMouse().reinitialize(width / this.width, height / this.height);
```
And this seems to fix it. Since people keep finding (and fixing!) bugs, I should really push out a small bugfix release soon.

**Comment by davidbecker** [comment]
I believe we get a rounding error this way -> all seems fine when the player is on the left side of the playing field, but the more the player moves to the right the calculation is more off. On this screenshot the mouse hovers directly over the player tile:
![fov3](https://cloud.githubusercontent.com/assets/1927731/9611561/a1ce3010-50e0-11e5-9e2f-2cc701082b00.png)

And a new error slipped in:
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 81
	at squidpony.gdx.examples.EverythingDemo$2.mouseMoved(EverythingDemo.java:257)
	at squidpony.squidgrid.gui.gdx.SquidMouse.mouseMoved(SquidMouse.java:203)
	at squidpony.squidgrid.gui.gdx.SquidInput.mouseMoved(SquidInput.java:314)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:312)
```
