### ISSUE TITLE
Add a new "grass" FillEffect in DungeonGenerator

### ISSUE THREAD

**Issue by smelc** [SquidPony/SquidLib#91]
It'd be nice to have an effect to generate grass (represented by " in brogue) in DungeonGenerator. I think it can be generated like water, but I'm not confident in doing it myself; because the code about that in DungeonGenerator is pretty tricky.

**Comment by tommyettinger** [comment]
This is a good suggestion, by the way. It doesn't hurt that it needed almost exactly the same code used for adding water!
