### ISSUE TITLE
Change the repo tagline, general site cleanup

### ISSUE THREAD

**Issue by tommyettinger** [SquidPony/SquidLib#96]
Currently the tagline that shows up in searches for SquidLib says:

Useful tools for working with Grid World in Java Swing panels. Comments and suggestions are very welcome! http://squidpony.com

Except we no longer support Swing, Grid World is a bit confusing (could we find a better term for tools for grid-based games?), and I think the URL is down. I think @SquidPony is the only one who can change the tagline? My suggestion for a tagline is:

Useful tools for roguelike, role-playing, strategy, and other grid-based games in Java. Feedback is welcome!

I keep finding code bugs that I want to have fixed by 3.0.0 final, which should be soon, but I hope we can get the repo to look a bit cleaner by then. Adding new tutorials, maybe to the wiki, is going to be important.

**Comment by smelc** [comment]
:+1: for the proposed tagline

**Comment by davidbecker** [comment]
:+1: for the tagline as well from me
I'm afraid that I won't be of much help for the clean-up phase before 3.0.0 since I probably don't have much time for side-projects until mid-January

**Comment by SquidPony** [comment]
Changed the tagline and removed the link to my under (very long) maintenance site.

**Comment by tommyettinger** [comment]
Cleanup is still under way, but thanks @SquidPony for changing the tagline!

**Comment by SquidPony** [comment]
I'm calling this closed due to the open ended nature of the site cleanup part being the part left and that will likely always be an issue while the project is alive
