### ISSUE TITLE
DungeonGenerator always generates water

### ISSUE THREAD

**Issue by smelc** [SquidPony/SquidLib#98]
This is visible if you comment out the addWater call in `EverythingDemo`. The generated grid has (quite a large) pool of deep water. I think this isn't the intended behavior of `DungeonGenerator`. This changed somewhere in between db43d4740c48a8ba091aab9ddc2b and 1b264517ae434a085cdc825ffe4e4f7f2f4dfdc1.

**Comment by tommyettinger** [comment]
I'm pretty sure I know what causes this, even though I thought I had a check for it... I'll take a look.

**Comment by tommyettinger** [comment]
The bug had to do with MultiSpill not updating the indices it used to mark each spill as "floor" or "water", so I'd have a water fill with 0.0 likelihood, which would never fill anything, and then the next one would be considered water anyway and would fill a floor area or something with water. It's fixed now, pretty sure.

**Comment by smelc** [comment]
I confirm that this fixed the problem in my roguelike. Thank you :+1:
